name: CI Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Update to the latest version

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2  # Update to the latest version
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Convert username to lowercase
        id: to-lower
        run: echo "username=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.username }}/practical-w:latest .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ env.username }}/practical-w:latest

